### ISSUE TITLE
Querying persons names from DbPedia

### ISSUE THREAD

**Issue by bhavikajalli** [jindrichmynarz/sparql-to-csv#1]
Hello,
I am trying to use your wrapper to query all the person names into a csv file.
I used the command `target/sparql_to_csv --endpoint <http://dbpedia.org/ontology/> --page-size 1000 \ paged_query.mustache > results.csv`
However I got the error:
`-bash: http://dbpedia.org/ontology/: No such file or directory`
Can you help me out?

**Comment by jindrichmynarz** [comment]
The DBpedia's SPARQL endpoint is at <http://dbpedia.org/sparql>, not <http://dbpedia.org/ontology/> (this is the namespace of DBpedia ontology). Moreover, when specifying the SPARQL endpoint's URL you should omit the angle brackets, which have special meaning in shell (i.e. redirect from/to file).

**Comment by bhavikajalli** [comment]
Thanks for clarifying that for me. I had another question. From my understanding of your instructions, I created a mustache called, person.mustache with the following code
`PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?name
WHERE {
?person dbo:birthDate ?birth .
?person rdfs:label ?name FILTER (lang(?name) = "en").
OPTIONAL { ?person dbo:deathDate ?death . }
FILTER (?birth > "1900-01-01"^^xsd:date) .
}
ORDER BY (?name)`

And then I ran the command
`target/sparql_to_csv --endpoint http://dbpedia.org/sparql --page-size 1000 \ person.mustache > results.csv`
However, I am getting the error 
`File at person.mustache doesn't exist.`
What am I doing wrong?

**Comment by jindrichmynarz** [comment]
According to the error the file `person.mustache` doesn't exist. You might have saved it at another path than `person.mustache`.
